
package soap.vw.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GameServer", targetNamespace = "http://connect.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GameServer {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.UpdateResponse")
    @Action(input = "http://connect.soap/GameServer/updateRequest", output = "http://connect.soap/GameServer/updateResponse")
    public void update();

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.vw.webservice.Player
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPlayer", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.FindPlayer")
    @ResponseWrapper(localName = "findPlayerResponse", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.FindPlayerResponse")
    @Action(input = "http://connect.soap/GameServer/findPlayerRequest", output = "http://connect.soap/GameServer/findPlayerResponse")
    public Player findPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMove", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.SetMove")
    @ResponseWrapper(localName = "setMoveResponse", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.SetMoveResponse")
    @Action(input = "http://connect.soap/GameServer/setMoveRequest", output = "http://connect.soap/GameServer/setMoveResponse")
    public void setMove(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addClient", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.AddClient")
    @ResponseWrapper(localName = "addClientResponse", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.AddClientResponse")
    @Action(input = "http://connect.soap/GameServer/addClientRequest", output = "http://connect.soap/GameServer/addClientResponse")
    public String addClient();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "firstMove", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.FirstMove")
    @ResponseWrapper(localName = "firstMoveResponse", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.FirstMoveResponse")
    @Action(input = "http://connect.soap/GameServer/firstMoveRequest", output = "http://connect.soap/GameServer/firstMoveResponse")
    public void firstMove(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Player arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "skipMove", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.SkipMove")
    @ResponseWrapper(localName = "skipMoveResponse", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.SkipMoveResponse")
    @Action(input = "http://connect.soap/GameServer/skipMoveRequest", output = "http://connect.soap/GameServer/skipMoveResponse")
    public void skipMove(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendToClient", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.SendToClient")
    @ResponseWrapper(localName = "sendToClientResponse", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.SendToClientResponse")
    @Action(input = "http://connect.soap/GameServer/sendToClientRequest", output = "http://connect.soap/GameServer/sendToClientResponse")
    public String sendToClient();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendInfoToClient", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.SendInfoToClient")
    @ResponseWrapper(localName = "sendInfoToClientResponse", targetNamespace = "http://connect.soap/", className = "soap.vw.webservice.SendInfoToClientResponse")
    @Action(input = "http://connect.soap/GameServer/sendInfoToClientRequest", output = "http://connect.soap/GameServer/sendInfoToClientResponse")
    public void sendInfoToClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Player arg0);

}
